language: php

php:
    - '7.1'
    - '7.2'
    - '7.3'

install:
    - composer install

script:
    - vendor/bin/phpunit

after_success:
    - bash <(curl -s https://codecov.io/bash) -f build/logs/clover.xml
    - vendor/bin/test-reporter
