remote_theme: just-the-docs/just-the-docs

title: Public Key Cryptography Bundle

aux_links:
  Visit repository on GitHub: https://github.com/darkwebdesign/public-key-cryptography-bundle

collections:
  v1_3:
    permalink: "/docs/1.3/:path:output_ext"
    output: true
#  v5_3:
#    permalink: "/docs/5.3/:path:output_ext"
#    output: true
#  v5_2:
#    permalink: "/docs/5.2/:path:output_ext"
#    output: true
#  v5_1:
#    permalink: "/docs/5.1/:path:output_ext"
#    output: true
#  v5_0:
#    permalink: "/docs/5.0/:path:output_ext"
#    output: true

just_the_docs:
  collections:
    v1_3:
      name: v1.3 (latest)
      nav_exclude: false
      nav_fold: true
      search_exclude: false
#    v5_3:
#      name: v5.3
#      nav_exclude: false
#      nav_fold: true
#      search_exclude: true
#    v5_2:
#      name: v5.2
#      nav_exclude: false
#      nav_fold: true
#      search_exclude: true
#    v5_1:
#      name: v5.1
#      nav_exclude: false
#      nav_fold: true
#      search_exclude: true
#    v5_0:
#      name: v5.0
#      nav_exclude: false
#      nav_fold: true
#      search_exclude: true

callouts:
  info:
    title: Info
    color: blue
  warning:
    title: Warning
    color: yellow
  danger:
    title: Danger
    color: red
  grey-lt:
    color: grey-lt
  grey-dk:
    color: grey-dk
  purple:
    color: purple
  blue:
    color: blue
  green:
    color: green
  yellow:
    color: yellow
  red:
    color: red

plugins:
  - jekyll-redirect-from
